#!/bin/sh

panel &

bspc monitor DP-2 -d I II III IV V VI

bspc config border_width                    0
bspc config window_gap                      15
# bspc config top_padding                     10
bspc config single_monocle                  true
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config pointer_follows_monitor         true
bspc config focus_follows_pointer           true
bspc config click_to_focus                  true

# RULES

bspc rule -a '*:zathura'                  state=tiled

# Xorg config
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
xsetroot -cursor_name left_ptr
